<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250516195129 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE alternative (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statement TEXT NOT NULL, is_correct BOOLEAN NOT NULL, multiple_choice_question_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EFF5DFAEB3EBF2 ON alternative (multiple_choice_question_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE multiple_choice_question (id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statement TEXT NOT NULL, maximum_possible_points INT NOT NULL, quiz_id INT NOT NULL, discriminator VARCHAR(255) NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_B6F7494E853CD175 ON question (quiz_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE quiz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_id INT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_A412FA92AFC2B591 ON quiz (module_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE alternative ADD CONSTRAINT FK_EFF5DFAEB3EBF2 FOREIGN KEY (multiple_choice_question_id) REFERENCES multiple_choice_question (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE multiple_choice_question ADD CONSTRAINT FK_24557253BF396750 FOREIGN KEY (id) REFERENCES question (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE question ADD CONSTRAINT FK_B6F7494E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quiz ADD CONSTRAINT FK_A412FA92AFC2B591 FOREIGN KEY (module_id) REFERENCES module (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE alternative DROP CONSTRAINT FK_EFF5DFAEB3EBF2
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE multiple_choice_question DROP CONSTRAINT FK_24557253BF396750
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE question DROP CONSTRAINT FK_B6F7494E853CD175
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE quiz DROP CONSTRAINT FK_A412FA92AFC2B591
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE alternative
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE multiple_choice_question
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE question
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE quiz
        SQL);
    }
}
